/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

package com.edu.sise.capas.gui;

import com.edu.sise.capas.entity.Usuario;
import com.edu.sise.capas.logic.UsuarioLogic;
import javax.swing.JOptionPane;


/**
 *
 * @author SEBASTIAN
 */
public class iFrmUsuarios extends javax.swing.JInternalFrame {
    UsuarioLogic logic = null;
    /** Creates new form iFrmUsuarios */
    public iFrmUsuarios() {
        initComponents();
        logic = new UsuarioLogic();
        logic.imprimirTB(tbListaUsuarios,logic.obtenerTodos());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnObtener = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtclave = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaUsuarios = new javax.swing.JTable();
        btnListar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminarr = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();

        setTitle("Mantenedor de Usuarios");

        btnObtener.setText("Obtener");
        btnObtener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObtenerActionPerformed(evt);
            }
        });

        jLabel1.setText("ID: ");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Clave:");

        tbListaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbListaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListaUsuarios);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminarr.setText("Eliminar");
        btnEliminarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarrActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        jLabel4.setText("BUSCAR:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnObtener)
                                    .addComponent(btnListar)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnAgregar)
                        .addGap(41, 41, 41)
                        .addComponent(btnModificar)
                        .addGap(40, 40, 40)
                        .addComponent(btnEliminarr)
                        .addGap(25, 25, 25)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnObtener))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnListar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtclave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminarr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnObtenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObtenerActionPerformed
        logic = new UsuarioLogic();
        int id = Integer.parseInt(txtID.getText()); 
        Usuario objUsuario = logic.obtenerUsuarioxID(id);
        if (objUsuario!=null){
            JOptionPane.showMessageDialog(null, "Bienvenido: " + objUsuario.getNombre());
        }else{
            JOptionPane.showMessageDialog(null,"Usuario no encontrado");
        }
    }//GEN-LAST:event_btnObtenerActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        logic = new UsuarioLogic();
        logic.imprimirTB(tbListaUsuarios,logic.obtenerTodos());
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
//        Usuario objUsuario = new Usuario();
//        int id ;
//        String nombre, clave;
//        id = Integer.parseInt(txtID.getText());
//        nombre = txtNombre.getText();
//        clave = txtClave.getText();
//        objUsuario.setId_usuario(id);
//        objUsuario.setNombre(nombre);
//        objUsuario.setClave(clave);
        logic = new UsuarioLogic();
        boolean rpta;
        rpta = logic.agregarUsuario(getUsuario());
        
        if(rpta){
            JOptionPane.showMessageDialog(null, "Se registro correctamente!!!");
        }else{
            JOptionPane.showMessageDialog(null, "No se pudo registras :(" );
        }
        logic.imprimirTB(tbListaUsuarios, logic.obtenerTodos());
               
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tbListaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaUsuariosMouseClicked
        // TODO add your handling code here:
        int fila;
        fila = tbListaUsuarios.getSelectedRow();
        int id;
        String nombre, clave;
        if(fila>=0){
            id = Integer.parseInt(tbListaUsuarios.getValueAt(fila, 0)+"");
            nombre = tbListaUsuarios.getValueAt(fila, 1)+"";
            clave = tbListaUsuarios.getValueAt(fila, 2)+"";
            txtID.setText(id+"");
            txtnombre.setText(nombre);
            txtclave.setText(clave);
            
        }
    }//GEN-LAST:event_tbListaUsuariosMouseClicked

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
//        Usuario objUsuario = new Usuario();
//        
//        objUsuario.setId_usuario(Integer.parseInt(txtID.getText()));
//        objUsuario.setNombre(txtnombre.getText());
//        objUsuario.setClave(txtclave.getText());
        
        logic = new UsuarioLogic();
        boolean rpta = logic.modificarUsuario(getUsuario());
        if(rpta){
            JOptionPane.showMessageDialog(null, "Se modifico correctamente");
        }else{
            JOptionPane.showMessageDialog(null, "No se pudo modificar :c");
        }
        
        logic.imprimirTB(tbListaUsuarios,logic.obtenerTodos());
        
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarrActionPerformed
        // TODO add your handling code here:
        
        int id ;
        String rpta; 
        boolean rptaEliminado;
        int fila = tbListaUsuarios.getSelectedRow();
        if (fila>=0){
            id = Integer.parseInt(tbListaUsuarios.getValueAt(fila, 0)+"");
            
            int valor = JOptionPane.showConfirmDialog(null, "¿Deseas realmente eliminar el registro?","SISTEMA",JOptionPane.YES_NO_OPTION);
            
            if(valor==JOptionPane.YES_OPTION){
            logic = new UsuarioLogic();
            rptaEliminado = logic.eliminarUsuario(id);
            if (rptaEliminado){
                JOptionPane.showMessageDialog(null, "Se elimino correctamente");
            }else{
                JOptionPane.showMessageDialog(null, "No se pudo eliminar :c");
            }
            logic.imprimirTB(tbListaUsuarios, logic.obtenerTodos());
            }
        }     
    }//GEN-LAST:event_btnEliminarrActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String nombreBuscar = txtbuscar.getText();
        logic = new UsuarioLogic();
        logic.imprimirTB(tbListaUsuarios, logic.buscarxNombre(nombreBuscar));
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtbuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyPressed
    
    }//GEN-LAST:event_txtbuscarKeyPressed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        // TODO add your handling code here:
         String nombreBuscar = txtbuscar.getText();
        logic = new UsuarioLogic();
        logic.imprimirTB(tbListaUsuarios, logic.buscarxNombre(nombreBuscar));
    }//GEN-LAST:event_txtbuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminarr;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnObtener;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbListaUsuarios;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtbuscar;
    private javax.swing.JTextField txtclave;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables

    Usuario getUsuario(){
        Usuario objUsuario = new Usuario(
                Integer.parseInt(txtID.getText()),
                txtnombre.getText(),
                txtclave.getText()
        );
        
        return objUsuario;
    }
}
